### PR TITLE
Refactor new tab and fix some issues

### PR DESCRIPTION
**Pull request by metarmask**
- Move list of fortune files to file
- Use defer attribute instead of DOMContentLoaded event
- Use flexbox for centering
- Replace loops with array methods
- Replace innerHTML and HTML escaping with textContent
- Replace $.ajax with fetch and async/await
- Remove jQM
- Fix tabs being counted as one character
- Fix extra space on cow
- Fix inconsistent spacing

Because we are in a Chrome extension environment we can use the latest and greatest features without transpiling, let's use that opportunity! (flexbox, fetch, async/await, array methods)

The list of fortune files will be easier to maintain if its a seperate file. Loading it only adds about 4ms.

Libraries that are used for only a couple of things on a page that is going to be loaded many, many times is unneccessary.

### CODE REVIEW

**Comment by tanishq-dubey** [comment]
Hey there! Thanks for the fixes! If you could fast forward your branch to include the changes I made to master (options menu, cow selection, etc.) I would definitely merge the changes.

**Comment by metarmask** [comment]
Do you want me to refactor the options to have the same formatting as the new tab script and also make use of the cow index file?

I think this repository could benefit from some contribution guidelines because indentation, spacing and variable types are inconsistent right now.

**Comment by tanishq-dubey** [comment]
Are there set JS guidelines? I would be super grateful for you help with that! This was my first real JS project so all this is a bit new to me.

**Comment by metarmask** [comment]
No, everyone has different preferences. Many place a file with [ESLint rules](http://eslint.org/docs/rules/#stylistic-issues) in their repos to enforce a certain style. If you're not sure which style to pick you can use the same as a popular repository. Love this project by the way, such a great idea.

**Pull request merged**
